// Code generated by ent, DO NOT EDIT.

package ticketevent

import (
	"database-concurrency/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTicketID), v))
	})
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldType), v))
	})
}

// Versions applies equality check predicate on the "versions" field. It's identical to VersionsEQ.
func Versions(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldVersions), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTicketID), v))
	})
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTicketID), v))
	})
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...uuid.UUID) predicate.TicketEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldTicketID), v...))
	})
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...uuid.UUID) predicate.TicketEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldTicketID), v...))
	})
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUserID), v))
	})
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.TicketEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUserID), v...))
	})
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.TicketEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUserID), v...))
	})
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldType), v))
	})
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldType), v))
	})
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.TicketEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldType), v...))
	})
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.TicketEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldType), v...))
	})
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldType), v))
	})
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldType), v))
	})
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldType), v))
	})
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldType), v))
	})
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldType), v))
	})
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldType), v))
	})
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldType), v))
	})
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldType), v))
	})
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldType), v))
	})
}

// VersionsEQ applies the EQ predicate on the "versions" field.
func VersionsEQ(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldVersions), v))
	})
}

// VersionsNEQ applies the NEQ predicate on the "versions" field.
func VersionsNEQ(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldVersions), v))
	})
}

// VersionsIn applies the In predicate on the "versions" field.
func VersionsIn(vs ...string) predicate.TicketEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldVersions), v...))
	})
}

// VersionsNotIn applies the NotIn predicate on the "versions" field.
func VersionsNotIn(vs ...string) predicate.TicketEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldVersions), v...))
	})
}

// VersionsGT applies the GT predicate on the "versions" field.
func VersionsGT(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldVersions), v))
	})
}

// VersionsGTE applies the GTE predicate on the "versions" field.
func VersionsGTE(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldVersions), v))
	})
}

// VersionsLT applies the LT predicate on the "versions" field.
func VersionsLT(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldVersions), v))
	})
}

// VersionsLTE applies the LTE predicate on the "versions" field.
func VersionsLTE(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldVersions), v))
	})
}

// VersionsContains applies the Contains predicate on the "versions" field.
func VersionsContains(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldVersions), v))
	})
}

// VersionsHasPrefix applies the HasPrefix predicate on the "versions" field.
func VersionsHasPrefix(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldVersions), v))
	})
}

// VersionsHasSuffix applies the HasSuffix predicate on the "versions" field.
func VersionsHasSuffix(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldVersions), v))
	})
}

// VersionsEqualFold applies the EqualFold predicate on the "versions" field.
func VersionsEqualFold(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldVersions), v))
	})
}

// VersionsContainsFold applies the ContainsFold predicate on the "versions" field.
func VersionsContainsFold(v string) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldVersions), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TicketEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TicketEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TicketEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TicketEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(TicketTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.Ticket) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(TicketInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TicketEvent) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TicketEvent) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TicketEvent) predicate.TicketEvent {
	return predicate.TicketEvent(func(s *sql.Selector) {
		p(s.Not())
	})
}
