FROM golang:1.18 as builder
RUN mkdir /build
WORKDIR /build
COPY . .

RUN apt-get update
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go install -mod=mod -v ./...
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -mod=mod -o /go/bin/idgen ./cmd/idgen/...

FROM alpine:3.10 as runner
ARG DEFAULT_PORT
RUN apk --no-cache add ca-certificates
WORKDIR /

COPY --from=builder /go/bin/* /usr/bin/

EXPOSE ${DEFAULT_PORT}