// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in database-concurrency/ent/runtime.go

const (
	Version = "v0.11.5-0.20221123165602-b6a475f066c4"           // Version of ent codegen.
	Sum     = "h1:1xgAKKKKYqDiO/iPSS5apQdVAF5gre688hddRUBynck=" // Sum of ent codegen.
)
