// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database-concurrency/ent/createticketlog"
	"database-concurrency/ent/predicate"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CreateTicketLogDelete is the builder for deleting a CreateTicketLog entity.
type CreateTicketLogDelete struct {
	config
	hooks    []Hook
	mutation *CreateTicketLogMutation
}

// Where appends a list predicates to the CreateTicketLogDelete builder.
func (ctld *CreateTicketLogDelete) Where(ps ...predicate.CreateTicketLog) *CreateTicketLogDelete {
	ctld.mutation.Where(ps...)
	return ctld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ctld *CreateTicketLogDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ctld.hooks) == 0 {
		affected, err = ctld.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CreateTicketLogMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ctld.mutation = mutation
			affected, err = ctld.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ctld.hooks) - 1; i >= 0; i-- {
			if ctld.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ctld.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ctld.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctld *CreateTicketLogDelete) ExecX(ctx context.Context) int {
	n, err := ctld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ctld *CreateTicketLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: createticketlog.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: createticketlog.FieldID,
			},
		},
	}
	if ps := ctld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ctld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// CreateTicketLogDeleteOne is the builder for deleting a single CreateTicketLog entity.
type CreateTicketLogDeleteOne struct {
	ctld *CreateTicketLogDelete
}

// Exec executes the deletion query.
func (ctldo *CreateTicketLogDeleteOne) Exec(ctx context.Context) error {
	n, err := ctldo.ctld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{createticketlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ctldo *CreateTicketLogDeleteOne) ExecX(ctx context.Context) {
	ctldo.ctld.ExecX(ctx)
}
