// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database-concurrency/ent/predicate"
	"database-concurrency/ent/serviceprodiver"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServiceProdiverUpdate is the builder for updating ServiceProdiver entities.
type ServiceProdiverUpdate struct {
	config
	hooks    []Hook
	mutation *ServiceProdiverMutation
}

// Where appends a list predicates to the ServiceProdiverUpdate builder.
func (spu *ServiceProdiverUpdate) Where(ps ...predicate.ServiceProdiver) *ServiceProdiverUpdate {
	spu.mutation.Where(ps...)
	return spu
}

// SetName sets the "name" field.
func (spu *ServiceProdiverUpdate) SetName(s string) *ServiceProdiverUpdate {
	spu.mutation.SetName(s)
	return spu
}

// SetEmail sets the "email" field.
func (spu *ServiceProdiverUpdate) SetEmail(s string) *ServiceProdiverUpdate {
	spu.mutation.SetEmail(s)
	return spu
}

// SetPhone sets the "phone" field.
func (spu *ServiceProdiverUpdate) SetPhone(s string) *ServiceProdiverUpdate {
	spu.mutation.SetPhone(s)
	return spu
}

// SetVerdorRef sets the "verdor_ref" field.
func (spu *ServiceProdiverUpdate) SetVerdorRef(s string) *ServiceProdiverUpdate {
	spu.mutation.SetVerdorRef(s)
	return spu
}

// SetCreatedAt sets the "created_at" field.
func (spu *ServiceProdiverUpdate) SetCreatedAt(t time.Time) *ServiceProdiverUpdate {
	spu.mutation.SetCreatedAt(t)
	return spu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (spu *ServiceProdiverUpdate) SetNillableCreatedAt(t *time.Time) *ServiceProdiverUpdate {
	if t != nil {
		spu.SetCreatedAt(*t)
	}
	return spu
}

// SetUpdatedAt sets the "updated_at" field.
func (spu *ServiceProdiverUpdate) SetUpdatedAt(t time.Time) *ServiceProdiverUpdate {
	spu.mutation.SetUpdatedAt(t)
	return spu
}

// Mutation returns the ServiceProdiverMutation object of the builder.
func (spu *ServiceProdiverUpdate) Mutation() *ServiceProdiverMutation {
	return spu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (spu *ServiceProdiverUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	spu.defaults()
	if len(spu.hooks) == 0 {
		affected, err = spu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ServiceProdiverMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			spu.mutation = mutation
			affected, err = spu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(spu.hooks) - 1; i >= 0; i-- {
			if spu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = spu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, spu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (spu *ServiceProdiverUpdate) SaveX(ctx context.Context) int {
	affected, err := spu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (spu *ServiceProdiverUpdate) Exec(ctx context.Context) error {
	_, err := spu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (spu *ServiceProdiverUpdate) ExecX(ctx context.Context) {
	if err := spu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (spu *ServiceProdiverUpdate) defaults() {
	if _, ok := spu.mutation.UpdatedAt(); !ok {
		v := serviceprodiver.UpdateDefaultUpdatedAt()
		spu.mutation.SetUpdatedAt(v)
	}
}

func (spu *ServiceProdiverUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   serviceprodiver.Table,
			Columns: serviceprodiver.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: serviceprodiver.FieldID,
			},
		},
	}
	if ps := spu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := spu.mutation.Name(); ok {
		_spec.SetField(serviceprodiver.FieldName, field.TypeString, value)
	}
	if value, ok := spu.mutation.Email(); ok {
		_spec.SetField(serviceprodiver.FieldEmail, field.TypeString, value)
	}
	if value, ok := spu.mutation.Phone(); ok {
		_spec.SetField(serviceprodiver.FieldPhone, field.TypeString, value)
	}
	if value, ok := spu.mutation.VerdorRef(); ok {
		_spec.SetField(serviceprodiver.FieldVerdorRef, field.TypeString, value)
	}
	if value, ok := spu.mutation.CreatedAt(); ok {
		_spec.SetField(serviceprodiver.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := spu.mutation.UpdatedAt(); ok {
		_spec.SetField(serviceprodiver.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, spu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serviceprodiver.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// ServiceProdiverUpdateOne is the builder for updating a single ServiceProdiver entity.
type ServiceProdiverUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServiceProdiverMutation
}

// SetName sets the "name" field.
func (spuo *ServiceProdiverUpdateOne) SetName(s string) *ServiceProdiverUpdateOne {
	spuo.mutation.SetName(s)
	return spuo
}

// SetEmail sets the "email" field.
func (spuo *ServiceProdiverUpdateOne) SetEmail(s string) *ServiceProdiverUpdateOne {
	spuo.mutation.SetEmail(s)
	return spuo
}

// SetPhone sets the "phone" field.
func (spuo *ServiceProdiverUpdateOne) SetPhone(s string) *ServiceProdiverUpdateOne {
	spuo.mutation.SetPhone(s)
	return spuo
}

// SetVerdorRef sets the "verdor_ref" field.
func (spuo *ServiceProdiverUpdateOne) SetVerdorRef(s string) *ServiceProdiverUpdateOne {
	spuo.mutation.SetVerdorRef(s)
	return spuo
}

// SetCreatedAt sets the "created_at" field.
func (spuo *ServiceProdiverUpdateOne) SetCreatedAt(t time.Time) *ServiceProdiverUpdateOne {
	spuo.mutation.SetCreatedAt(t)
	return spuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (spuo *ServiceProdiverUpdateOne) SetNillableCreatedAt(t *time.Time) *ServiceProdiverUpdateOne {
	if t != nil {
		spuo.SetCreatedAt(*t)
	}
	return spuo
}

// SetUpdatedAt sets the "updated_at" field.
func (spuo *ServiceProdiverUpdateOne) SetUpdatedAt(t time.Time) *ServiceProdiverUpdateOne {
	spuo.mutation.SetUpdatedAt(t)
	return spuo
}

// Mutation returns the ServiceProdiverMutation object of the builder.
func (spuo *ServiceProdiverUpdateOne) Mutation() *ServiceProdiverMutation {
	return spuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (spuo *ServiceProdiverUpdateOne) Select(field string, fields ...string) *ServiceProdiverUpdateOne {
	spuo.fields = append([]string{field}, fields...)
	return spuo
}

// Save executes the query and returns the updated ServiceProdiver entity.
func (spuo *ServiceProdiverUpdateOne) Save(ctx context.Context) (*ServiceProdiver, error) {
	var (
		err  error
		node *ServiceProdiver
	)
	spuo.defaults()
	if len(spuo.hooks) == 0 {
		node, err = spuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ServiceProdiverMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			spuo.mutation = mutation
			node, err = spuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(spuo.hooks) - 1; i >= 0; i-- {
			if spuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = spuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, spuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*ServiceProdiver)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ServiceProdiverMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (spuo *ServiceProdiverUpdateOne) SaveX(ctx context.Context) *ServiceProdiver {
	node, err := spuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (spuo *ServiceProdiverUpdateOne) Exec(ctx context.Context) error {
	_, err := spuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (spuo *ServiceProdiverUpdateOne) ExecX(ctx context.Context) {
	if err := spuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (spuo *ServiceProdiverUpdateOne) defaults() {
	if _, ok := spuo.mutation.UpdatedAt(); !ok {
		v := serviceprodiver.UpdateDefaultUpdatedAt()
		spuo.mutation.SetUpdatedAt(v)
	}
}

func (spuo *ServiceProdiverUpdateOne) sqlSave(ctx context.Context) (_node *ServiceProdiver, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   serviceprodiver.Table,
			Columns: serviceprodiver.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: serviceprodiver.FieldID,
			},
		},
	}
	id, ok := spuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServiceProdiver.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := spuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serviceprodiver.FieldID)
		for _, f := range fields {
			if !serviceprodiver.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != serviceprodiver.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := spuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := spuo.mutation.Name(); ok {
		_spec.SetField(serviceprodiver.FieldName, field.TypeString, value)
	}
	if value, ok := spuo.mutation.Email(); ok {
		_spec.SetField(serviceprodiver.FieldEmail, field.TypeString, value)
	}
	if value, ok := spuo.mutation.Phone(); ok {
		_spec.SetField(serviceprodiver.FieldPhone, field.TypeString, value)
	}
	if value, ok := spuo.mutation.VerdorRef(); ok {
		_spec.SetField(serviceprodiver.FieldVerdorRef, field.TypeString, value)
	}
	if value, ok := spuo.mutation.CreatedAt(); ok {
		_spec.SetField(serviceprodiver.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := spuo.mutation.UpdatedAt(); ok {
		_spec.SetField(serviceprodiver.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ServiceProdiver{config: spuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, spuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serviceprodiver.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
