// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database-concurrency/ent/serviceprodiver"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ServiceProdiverCreate is the builder for creating a ServiceProdiver entity.
type ServiceProdiverCreate struct {
	config
	mutation *ServiceProdiverMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (spc *ServiceProdiverCreate) SetName(s string) *ServiceProdiverCreate {
	spc.mutation.SetName(s)
	return spc
}

// SetEmail sets the "email" field.
func (spc *ServiceProdiverCreate) SetEmail(s string) *ServiceProdiverCreate {
	spc.mutation.SetEmail(s)
	return spc
}

// SetPhone sets the "phone" field.
func (spc *ServiceProdiverCreate) SetPhone(s string) *ServiceProdiverCreate {
	spc.mutation.SetPhone(s)
	return spc
}

// SetVerdorRef sets the "verdor_ref" field.
func (spc *ServiceProdiverCreate) SetVerdorRef(s string) *ServiceProdiverCreate {
	spc.mutation.SetVerdorRef(s)
	return spc
}

// SetCreatedAt sets the "created_at" field.
func (spc *ServiceProdiverCreate) SetCreatedAt(t time.Time) *ServiceProdiverCreate {
	spc.mutation.SetCreatedAt(t)
	return spc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (spc *ServiceProdiverCreate) SetNillableCreatedAt(t *time.Time) *ServiceProdiverCreate {
	if t != nil {
		spc.SetCreatedAt(*t)
	}
	return spc
}

// SetUpdatedAt sets the "updated_at" field.
func (spc *ServiceProdiverCreate) SetUpdatedAt(t time.Time) *ServiceProdiverCreate {
	spc.mutation.SetUpdatedAt(t)
	return spc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (spc *ServiceProdiverCreate) SetNillableUpdatedAt(t *time.Time) *ServiceProdiverCreate {
	if t != nil {
		spc.SetUpdatedAt(*t)
	}
	return spc
}

// SetID sets the "id" field.
func (spc *ServiceProdiverCreate) SetID(u uuid.UUID) *ServiceProdiverCreate {
	spc.mutation.SetID(u)
	return spc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (spc *ServiceProdiverCreate) SetNillableID(u *uuid.UUID) *ServiceProdiverCreate {
	if u != nil {
		spc.SetID(*u)
	}
	return spc
}

// Mutation returns the ServiceProdiverMutation object of the builder.
func (spc *ServiceProdiverCreate) Mutation() *ServiceProdiverMutation {
	return spc.mutation
}

// Save creates the ServiceProdiver in the database.
func (spc *ServiceProdiverCreate) Save(ctx context.Context) (*ServiceProdiver, error) {
	var (
		err  error
		node *ServiceProdiver
	)
	spc.defaults()
	if len(spc.hooks) == 0 {
		if err = spc.check(); err != nil {
			return nil, err
		}
		node, err = spc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ServiceProdiverMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = spc.check(); err != nil {
				return nil, err
			}
			spc.mutation = mutation
			if node, err = spc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(spc.hooks) - 1; i >= 0; i-- {
			if spc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = spc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, spc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*ServiceProdiver)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ServiceProdiverMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (spc *ServiceProdiverCreate) SaveX(ctx context.Context) *ServiceProdiver {
	v, err := spc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (spc *ServiceProdiverCreate) Exec(ctx context.Context) error {
	_, err := spc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (spc *ServiceProdiverCreate) ExecX(ctx context.Context) {
	if err := spc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (spc *ServiceProdiverCreate) defaults() {
	if _, ok := spc.mutation.CreatedAt(); !ok {
		v := serviceprodiver.DefaultCreatedAt()
		spc.mutation.SetCreatedAt(v)
	}
	if _, ok := spc.mutation.UpdatedAt(); !ok {
		v := serviceprodiver.DefaultUpdatedAt()
		spc.mutation.SetUpdatedAt(v)
	}
	if _, ok := spc.mutation.ID(); !ok {
		v := serviceprodiver.DefaultID()
		spc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (spc *ServiceProdiverCreate) check() error {
	if _, ok := spc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ServiceProdiver.name"`)}
	}
	if _, ok := spc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "ServiceProdiver.email"`)}
	}
	if _, ok := spc.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "ServiceProdiver.phone"`)}
	}
	if _, ok := spc.mutation.VerdorRef(); !ok {
		return &ValidationError{Name: "verdor_ref", err: errors.New(`ent: missing required field "ServiceProdiver.verdor_ref"`)}
	}
	if _, ok := spc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ServiceProdiver.created_at"`)}
	}
	if _, ok := spc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ServiceProdiver.updated_at"`)}
	}
	return nil
}

func (spc *ServiceProdiverCreate) sqlSave(ctx context.Context) (*ServiceProdiver, error) {
	_node, _spec := spc.createSpec()
	if err := sqlgraph.CreateNode(ctx, spc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (spc *ServiceProdiverCreate) createSpec() (*ServiceProdiver, *sqlgraph.CreateSpec) {
	var (
		_node = &ServiceProdiver{config: spc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: serviceprodiver.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: serviceprodiver.FieldID,
			},
		}
	)
	if id, ok := spc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := spc.mutation.Name(); ok {
		_spec.SetField(serviceprodiver.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := spc.mutation.Email(); ok {
		_spec.SetField(serviceprodiver.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := spc.mutation.Phone(); ok {
		_spec.SetField(serviceprodiver.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := spc.mutation.VerdorRef(); ok {
		_spec.SetField(serviceprodiver.FieldVerdorRef, field.TypeString, value)
		_node.VerdorRef = value
	}
	if value, ok := spc.mutation.CreatedAt(); ok {
		_spec.SetField(serviceprodiver.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := spc.mutation.UpdatedAt(); ok {
		_spec.SetField(serviceprodiver.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ServiceProdiverCreateBulk is the builder for creating many ServiceProdiver entities in bulk.
type ServiceProdiverCreateBulk struct {
	config
	builders []*ServiceProdiverCreate
}

// Save creates the ServiceProdiver entities in the database.
func (spcb *ServiceProdiverCreateBulk) Save(ctx context.Context) ([]*ServiceProdiver, error) {
	specs := make([]*sqlgraph.CreateSpec, len(spcb.builders))
	nodes := make([]*ServiceProdiver, len(spcb.builders))
	mutators := make([]Mutator, len(spcb.builders))
	for i := range spcb.builders {
		func(i int, root context.Context) {
			builder := spcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServiceProdiverMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, spcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, spcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, spcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (spcb *ServiceProdiverCreateBulk) SaveX(ctx context.Context) []*ServiceProdiver {
	v, err := spcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (spcb *ServiceProdiverCreateBulk) Exec(ctx context.Context) error {
	_, err := spcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (spcb *ServiceProdiverCreateBulk) ExecX(ctx context.Context) {
	if err := spcb.Exec(ctx); err != nil {
		panic(err)
	}
}
