// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database-concurrency/ent/predicate"
	"database-concurrency/ent/ticketevent"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TicketEventDelete is the builder for deleting a TicketEvent entity.
type TicketEventDelete struct {
	config
	hooks    []Hook
	mutation *TicketEventMutation
}

// Where appends a list predicates to the TicketEventDelete builder.
func (ted *TicketEventDelete) Where(ps ...predicate.TicketEvent) *TicketEventDelete {
	ted.mutation.Where(ps...)
	return ted
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ted *TicketEventDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ted.hooks) == 0 {
		affected, err = ted.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TicketEventMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ted.mutation = mutation
			affected, err = ted.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ted.hooks) - 1; i >= 0; i-- {
			if ted.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ted.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ted.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ted *TicketEventDelete) ExecX(ctx context.Context) int {
	n, err := ted.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ted *TicketEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: ticketevent.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: ticketevent.FieldID,
			},
		},
	}
	if ps := ted.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ted.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// TicketEventDeleteOne is the builder for deleting a single TicketEvent entity.
type TicketEventDeleteOne struct {
	ted *TicketEventDelete
}

// Exec executes the deletion query.
func (tedo *TicketEventDeleteOne) Exec(ctx context.Context) error {
	n, err := tedo.ted.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ticketevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tedo *TicketEventDeleteOne) ExecX(ctx context.Context) {
	tedo.ted.ExecX(ctx)
}
