// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CreateTicketLog is the predicate function for createticketlog builders.
type CreateTicketLog func(*sql.Selector)

// ServiceProdiver is the predicate function for serviceprodiver builders.
type ServiceProdiver func(*sql.Selector)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)

// TicketEvent is the predicate function for ticketevent builders.
type TicketEvent func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
